### ISSUE TITLE
아이콘 추가에 기여해주세요

### ISSUE THREAD

**Issue by chnwu-newlec** [newlecture-corp/newtil-css#103]
newtil-css 아이콘 목록에 없는 아이콘 추가에 기여해주세요!

## newtil-css의 현재 아이콘 목록

https://newlecture-corp.github.io/newtil-css/icons/list.html

## 아이콘 링크
https://phosphoricons.com/

### 1. 아이콘 저장하기
-  newtil-css에 없는 아이콘을 [phosphoricons](https://phosphoricons.com/)에서 찾아 저장합니다.
 <span style="display:flex;"> 이때, <img width="75" alt="스크린샷 2024-03-15 오전 11 46 16" src="https://github.com/newlecture-corp/newtil-css/assets/125777585/6bd0ad79-153b-481f-b41f-51563b3d0cb4" style="display:inline">를 눌러 저장합니다.</span>

### 2. 파일 이름 변경하기
`phosphoricons`에서는 파일이름 표기를 `파일-이름.svg` 형태인데요. `파일_이름.svg`으로 변경해줍니다. 즉, 모든 하이픈(`-`)을 언더바(`_`)로 수정합니다.

### 3. 아이콘을 newtil-css에 추가하기
1. 다운로드 받은 아이콘 파일을 `newtil-css/packages/icon` 경로에 추가합니다.
  ex ) `newtil-css/packages/icon/아이콘_이름.svg`
2. `newtil-css/packages/css/icon.css` 파일을 편집기로 열어 가장 마지막 라인에 코드를 추가합니다
```css
.icon\:아이콘_이름::before,
.icon\:아이콘_이름::after {
  -webkit-mask-image: url("../icon/아이콘_이름.svg");
  mask-image: url("../icon/아이콘_이름.svg");
}
```
