### ISSUE TITLE
report_doc: 아이콘 시작하기 #아이콘 색

### ISSUE THREAD

**Issue by K19619** [newlecture-corp/newtil-css#122]
https://newlecture-corp.github.io/newtil-css/icons/getting-started.html#%E1%84%8B%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%8F%E1%85%A9%E1%86%AB-%E1%84%89%E1%85%A2%E1%86%A8

저희 프로젝트에서는 main 컬러를 6개 레벨까지 추가한 상태이고, `color-main-5` 을 이용해서 icon색을 바꾸고 싶습니다. 
하지만 유틸리티가 `icon-color:main-3`  까지밖에 지원을 안해, 색을 바꾸지 못하고 있습니다.
그래서 `icon-color:main-5` 라는 유틸리티를 만드려고 하는데 어떻게 만들면 되는지 몰라 문의드렸습니다.

**Comment by hanHappy** [comment]
안녕하세요 @K19619 님! 문의 주셔서 감사합니다.

말씀해주신 것과 같이 Newtil CSS는 세 단계의 색상 시스템을 제공하고 있으며, 그 이상의 단계가 필요한 경우 별도의 설정이 필요합니다.

아이콘에 main-5단계의 색상을 적용하는 방법에 대해 답변드리겠습니다.

1. root.css(혹은 custom.css 등)에 원하는 단계의 색상을 추가합니다.
```css
:root{
  --color-main-1: #99c842;
  --color-main-2: #85b132;
  --color-main-3: #759d2a;
  --color-main-4: #newcolor;
  --color-main-5: #newcolor;
}
```
테마 커스터마이징에 대한 자세한 내용은 [여기](https://newlecture-corp.github.io/newtil-css/guide/customizing.html)를 참고해주세요 :)

2. root.css에 icon-color 유틸 클래스를 추가합니다.
```css
.icon-color\:main-4::before {
  background-color: var(--color-main-4);
}
.icon-color\:main-5::before {
  background-color: var(--color-main-5);
}
```

3. 추가한 유틸 클래스 적용
```html
<span class=icon icon:star icon-color:main-5>즐겨찾기</span>
```

** 위 설정은 아이콘 색상에만 해당합니다. 그외의 요소에 4, 5단계 색상을 적용하고 싶다면 위와 같은 방식으로 유틸 클래스를 작성해주셔야 합니다.
